# Generated by Django 4.2.9 on 2024-02-15 06:53

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')], verbose_name='season')),
                ('current', models.BooleanField(default=False, verbose_name='current')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_seasons', to='football.league', verbose_name='league')),
            ],
            options={
                'verbose_name': 'football leagueseason',
                'verbose_name_plural': 'football leagueseasons',
                'db_table': 'football_league_season',
                'ordering': ('-season',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('logo', models.ImageField(max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage('teams'), upload_to='', verbose_name='logo')),
                ('default_league_season', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_teams', to='football.leagueseason', verbose_name='default season')),
            ],
        ),
        migrations.AddField(
            model_name='leagueseason',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='related_seasons', to='football.team', verbose_name='teams'),
        ),
        migrations.CreateModel(
            name='LeagueRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'Final'), (2, 'Semi-Finals'), (3, '3rd PlaceFinal'), (4, 'Quarter-Finals'), (5, '8th Finals')], default=0, verbose_name='round type')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_rounds', to='football.leagueseason', verbose_name='season')),
            ],
            options={
                'verbose_name': 'football leagueround',
                'verbose_name_plural': 'football leaguerounds',
                'db_table': 'football_league_round',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='week number')),
                ('venue', models.CharField(max_length=64, null=True, verbose_name='venue')),
                ('start_date', models.DateTimeField(null=True, verbose_name='start date')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_away_fixtures', to='football.team', verbose_name='away')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_home_fixtures', to='football.team', verbose_name='home')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_fixtures', to='football.leagueround', verbose_name='round')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leagueseason',
            constraint=models.UniqueConstraint(fields=('league', 'season'), name='unique_football_league_season'),
        ),
        migrations.AddConstraint(
            model_name='leagueround',
            constraint=models.UniqueConstraint(fields=('season', 'name'), name='unique_football_league_round'),
        ),
    ]
