# Generated by Django 5.0.1 on 2024-02-01 11:44

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'rejected'), (3, 'accepted')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'info of order',
                'db_table': 'orderinfo',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('property_one', models.FloatField(null=True)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(validators=[order.models.validate_between_zero_and_one])),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderinfo',
            constraint=models.UniqueConstraint(fields=('created_date', 'title'), name='created_title_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='orderinfo',
            unique_together={('created_date', 'title')},
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.orderinfo'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.ProductItem', to='order.product'),
        ),
    ]
