# Generated by Django 4.2.9 on 2024-03-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
            ],
        ),
    ]
