# Generated by Django 4.2.9 on 2024-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
