# Generated by Django 4.2.9 on 2024-02-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment_tag_alter_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
