# Generated by Django 4.2.9 on 2024-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('fellow', 'Fellow User'), ('warehouse', 'Warehouse Admin'), ('finance', 'Finance Admin'), ('super', 'Super Admin')], default='normal', max_length=16),
        ),
    ]
